### ISSUE TITLE
Beautify GUI icons

### ISSUE THREAD

**Issue by skaupper** [fhhagenberg-sqe-esd-ws20/elevator-control-center-team-a#10]
By now the icons used to represent different states are pretty different from each other.

The goals for the icons should be:
- Consistency: The different icons should have roughly different styles.
- Readability: e.g. the lines of the target floor icon are pretty thin which makes them hardly recognizable
- Positioning: It would be neat that each icon has its own position which does not change when other icons are enabled.

**Comment by MADITT** [comment]
linked pr contains the enhanced images.
