### ISSUE TITLE
Setting the committed direction at target floor

### ISSUE THREAD

**Issue by skaupper** [fhhagenberg-sqe-esd-ws20/elevator-control-center-team-a#11]
When arrived at the target floor the committed direction should change to uncommitted. This should also be resembled in the GUI!

**Comment by pagdot** [comment]
No, because the direction is used by passengers to decide whether to enter the elevator or not. Another approach how to deal with the situation is described in #17

**Comment by MADITT** [comment]
@pagdot a solution is given in the linked pr.

**Comment by pagdot** [comment]
yeah, sorry. I've been stupid

**Comment by skaupper** [comment]
> No, because the direction is used by passengers to decide whether to enter the elevator or not. Another approach how to deal with the situation is described in #17

In manual mode the passenger has nothing to decide upon.
Either way, I will provide a `setCommittedDirection` method, so the controller can handle it (which would be important for automatic mode).

**Comment by MADITT** [comment]
Gui will hide now the direction images if the direction is set to uncommitted. (No setting or changing of direction was implemented by my side.)
