### ISSUE TITLE
Beautify displaying of status information.

### ISSUE THREAD

**Issue by skaupper** [fhhagenberg-sqe-esd-ws20/elevator-control-center-team-a#14]
By now the title and value of different pieces of status information are both left aligned and not padded at all.
At the very least it should be padded. Best case would be to left align the title and right align the corresponding values. 

Consider displaying units for all values as well!

**Comment by skaupper** [comment]
For example:
![image](https://user-images.githubusercontent.com/1375320/104573858-b099a400-5655-11eb-90c3-65592fa99cb3.png)

**Comment by MADITT** [comment]
Linked pr contains new padding of status information.
