### ISSUE TITLE
Prepare presentation

### ISSUE THREAD

**Issue by skaupper** [fhhagenberg-sqe-esd-ws20/elevator-control-center-team-a#15]
- Prepare a short demonstration that runs the ECC connected to the Elevator Simulator
    - Demonstrate manual mode
    - Demonstrate automatic mode (if implemented)

</br>

- Explain how your team ensured project and product quality. Think of
    - Build automation / Continous integration
    - Automated test execution
    - Code coverage
    - Static analysis (e.g. SonarCloud)
    - Code reviews (e.g. GitHub Pull Requests)
    - Issue management
    - Testing techniques (Black box, white box, model based, state based, ...)

</br>

- [Nice-to-have] Give us more insights into your project/product, e.g.
    - Architectural overview
    - Lessons learned in test automation
    - Tricky problem you solved (especially concerning testing)
    - (whatever might be interesting)

**Comment by MADITT** [comment]
Added google doc to describe steps for presenting the application: https://docs.google.com/document/d/1FvY_J3Kx5PEo4c2Qxqemsix7ZnShKcB5dNoSpJIY2ro/edit?usp=sharing

**Comment by MADITT** [comment]
Added whole presentation flow. Please verify if this is correct or not. Additionally some further information are required (Talk about this when we next meet up.)
