### ISSUE TITLE
Elevator direction doesn't work correctly while standing still

### ISSUE THREAD

**Issue by pagdot** [fhhagenberg-sqe-esd-ws20/elevator-control-center-team-a#17]
The elevator is used by the passengers to decide on entering an elevator or not. This should be set

- if a target floor gets set in manual floor. Halting on a floor shouldn't change the direction
- the direction the elevator will be taking in automatic mode

**Comment by skaupper** [comment]
> if a target floor gets set in manual floor. Halting on a floor shouldn't change the direction

So, why exactly? For the manual mode the operator of the ECC decides whether the elevator is going up or down. Since the passengers cannot rely on the committed direction anyway either way is equally valid.

**Comment by pagdot** [comment]
I've been stupid
