### ISSUE TITLE
Change elevator transition based on window resize

### ISSUE THREAD

**Issue by MADITT** [fhhagenberg-sqe-esd-ws20/elevator-control-center-team-a#18]
Translation needs to be recalculated if the height of the window changes.

**Comment by MADITT** [comment]
@skaupper @pagdot Elevator still glitches out of the field even with added resize listener. Is this acceptable or should we focus more on solving this?

**Comment by skaupper** [comment]
The solution works. It may not be super pretty (especially if the elevator is at the top floor at the moment of resizing) but it is functional at least. If you have spare time you can invest some more of it into this issue but otherwise I am happy with it.
