### ISSUE TITLE
Failing to connect freezes the application.

### ISSUE THREAD

**Issue by skaupper** [fhhagenberg-sqe-esd-ws20/elevator-control-center-team-a#24]
First mentioned in the comments of #22, the application hangs if the connection is interrupted, meaning it does not respond to any user interaction.

**Comment by pagdot** [comment]
@MADITT Can you try to reproduce this behaviour? I wasn't able to reproduce it on my machine

**Comment by skaupper** [comment]
I do not know why it is not reproducible for you but I fixed the problem with #25 so this issues can be closed.
