### ISSUE TITLE
GUI glitches after reconnecting to simulator

### ISSUE THREAD

**Issue by skaupper** [fhhagenberg-sqe-esd-ws20/elevator-control-center-team-a#8]
After the application loses connection to the simulator it tries to reconnect to it with every update cycle.
As soon as the reconnecting succeeds the elevator visualization glitches.
![image](https://user-images.githubusercontent.com/1375320/104568010-d15efb00-564f-11eb-95b1-1deeabf0603c.png)

**Comment by pagdot** [comment]
It seems to be a synchronization issue. I'll refactor some code to deal with this issue

**Comment by pagdot** [comment]
Fixed in #16
